# Generated by Django 2.1.4 on 2019-01-06 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('likes', models.IntegerField(default=0, verbose_name='Лайки')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Post')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
