# Generated by Django 2.1 on 2018-09-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='status',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
