# Generated by Django 2.1 on 2018-09-12 20:50

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180912_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='../../../media'), upload_to=''),
        ),
    ]
