# Generated by Django 2.1 on 2018-09-19 15:01

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180912_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='../../src/media'), upload_to=''),
        ),
    ]
